export const INDEX_MARKETS = [
  { symbol: "^IXIC", ticker: "IXIC", name: "NASDAQ", nameKo: "나스닥 종합", region: "US" },
  { symbol: "^KS11", ticker: "KOSPI", name: "KOSPI", nameKo: "코스피", region: "KR" },
  { symbol: "^N225", ticker: "N225", name: "NIKKEI 225", nameKo: "닛케이 225", region: "JP" },
  { symbol: "^GSPC", ticker: "SPX", name: "S&P 500", nameKo: "S&P 500", region: "US" },
  { symbol: "^STOXX50E", ticker: "SX5E", name: "EURO STOXX 50", nameKo: "유로 스톡스 50", region: "EU" },
  { symbol: "^HSI", ticker: "HSI", name: "HANG SENG", nameKo: "항셍", region: "HK" },
];

export const COMPANY_MARKET_SYMBOLS = {
  sensetime: "0020.HK",
  nvidia: "NVDA",
  amd: "AMD",
  microsoft: "MSFT",
  palantir: "PLTR",
  tesla: "TSLA",
  tsmc: "TSM",
  asml: "ASML",
  arm: "ARM",
  samsung: "005930.KS",
  skhynix: "000660.KS",
  naver: "035420.KS",
  pony: "PONY",
  fanuc: "6954.T",
  recursion: "RXRX",
  mobileye: "MBLY",
  alibaba: "BABA",
  abb: "ABBN.SW",
  meta: "META",
  snowflake: "SNOW",
  appen: "APX.AX",
  elastic: "ESTC",
  datadog: "DDOG",
  amazon: "AMZN",
  alphabet: "GOOGL",
  oracle: "ORCL",
  tencent: "0700.HK",
  ibm: "IBM",
  salesforce: "CRM",
  servicenow: "NOW",
  sap: "SAP.DE",
  crowdstrike: "CRWD",
  paloalto: "PANW",
  sentinelone: "S",
  vertiv: "VRT",
  equinix: "EQIX",
  digitalrealty: "DLR",
  schneider: "SU.PA",
  eaton: "ETN",
  siemens: "SIE.DE",
  rockwell: "ROK",
  honeywell: "HON",
  dassault: "DSY.PA",
  planet: "PL",
  apple: "AAPL",
  sony: "6758.T",
  xiaomi: "1810.HK",
  grab: "GRAB",
  upstart: "UPST",
  nubank: "NU",
  lemonade: "LMND",
  symbotic: "SYM",
  doosanrobotics: "454910.KS",
  tempus: "TEM",
  schrodinger: "SDGR",
  abcellera: "ABCL",
  broadcom: "AVGO",
  micron: "MU",
  qualcomm: "QCOM",
};

export const FEATURED_COMPANY_IDS = [
  "nvidia",
  "microsoft",
  "tsmc",
  "samsung",
  "skhynix",
  "palantir",
  "broadcom",
  "vertiv",
  "crowdstrike",
  "openai",
  "anthropic",
];

export const FEATURED_NEWS_QUERIES = {
  nvidia: "NVIDIA",
  microsoft: "Microsoft",
  tsmc: "TSMC",
  samsung: "Samsung Electronics",
  skhynix: "SK hynix",
  palantir: "Palantir",
  broadcom: "Broadcom",
  vertiv: "Vertiv",
  crowdstrike: "CrowdStrike",
};

export const COMPANY_LOGOS = {
  nvidia: "nvidia.svg",
  microsoft: "microsoft.svg",
  tsmc: "tsmc.svg",
  samsung: "samsung.svg",
  skhynix: "skhynix.svg",
  palantir: "palantir.svg",
  broadcom: "broadcom.svg",
  vertiv: "vertiv.svg",
  crowdstrike: "crowdstrike.svg",
  openai: "openai.svg",
  anthropic: "anthropic.svg",
};

export const COUNTRY_CODES = {
  "United States": "US",
  "South Korea": "KR",
  Japan: "JP",
  Taiwan: "TW",
  China: "CN",
  "Hong Kong": "HK",
  France: "FR",
  Germany: "DE",
  Netherlands: "NL",
  "United Kingdom": "GB",
  Switzerland: "CH",
  Canada: "CA",
  Australia: "AU",
  India: "IN",
  Israel: "IL",
  "United Arab Emirates": "AE",
  Ireland: "IE",
  Singapore: "SG",
  Brazil: "BR",
};

export const ALL_SNAPSHOT_SYMBOLS = [
  ...INDEX_MARKETS.map((market) => market.symbol),
  ...new Set(Object.values(COMPANY_MARKET_SYMBOLS)),
];
